### ISSUE TITLE
Support aborting the mapping

### ISSUE THREAD

**Issue by niftylettuce** [sindresorhus/p-map#28] opened 2020-07-14 17:51 UTC
e.g. a few seconds into waiting for the promise to finish, we could increase concurrency due to CPU limit being lowered below 20%, to a concurrency of 5x or something.  Basically dynamic concurrency

**Comment by niftylettuce** [comment] 2020-07-14 17:54
Perhaps expose or pass a Symbol?

**Comment by sindresorhus** [comment] 2020-07-14 18:28
Where would you change the concurrency? Inside the map function?

**Comment by sindresorhus** [comment] 2020-07-14 18:28
> Perhaps expose or pass a Symbol?

Can you show an example of how that would be used?

**Comment by niftylettuce** [comment] 2020-07-14 18:58
Here's an example:

https://github.com/breejs/bree#nodejs-email-queue-job-scheduling-example

Regarding the Symbol, I'm not sure to be honest because there would need to be support for multiple instances somehow.

**Comment by niftylettuce** [comment] 2020-07-14 18:59
In the prior link shared, I am referencing this snippet:

```js
// handle cancellation (this is a very simple example)
if (parentPort)
  parentPort.once('message', message => {
    //
    // TODO: once we can manipulate concurrency option to p-map
    // we could make it `Number.MAX_VALUE` here to speed cancellation up
    // <https://github.com/sindresorhus/p-map/issues/28>
    //
    if (message === 'cancel') isCancelled = true;
  });
```

**Comment by sindresorhus** [comment] 2020-07-14 19:11
While I agree that the ability to dynamically change the concurrency could be useful, in the example you reference, I think what you actually want is the ability to abort the `p-map` call. Could maybe be something like `pMap.abort(mapper)`.

**Comment by niftylettuce** [comment] 2020-07-14 19:17
Yes that would be great!

**Comment by niftylettuce** [comment] 2020-07-14 19:17
Both would, but the latter you mention would solve the immediate issue.

**Comment by papb** [comment] 2020-07-14 21:12
@sindresorhus Interesting idea of using the mapper reference itself to abort, but wouldn't it be better to add an `.abort` method to the returned promise? Otherwise if someone calls `pMap` twice with the same mapper they might get an undesired behavior.

```diff
- await pMap(foo, bar);
+ const mapping = pMap(foo, bar);
+ setTimeout(mapping.abort, 5000);
+ await mapping;
```

**Comment by sindresorhus** [comment] 2021-02-21 13:28
> Otherwise if someone calls pMap twice with the same mapper they might get an undesired behavior.

Yeah, good point.

Maybe supporting [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController) would be an even better solution.

**Comment by sindresorhus** [comment] 2021-02-21 13:30
Duplicate of #31

**Closed by sindresorhus** 2021-02-21 13:30 UTC
Labels: enhancement, help wanted
